# Generated by Django 2.2.3 on 2019-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codeforces_rating',
            field=models.IntegerField(default=0),
        ),
    ]
