# Generated by Django 2.2.3 on 2019-07-31 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_codeforces_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rank', models.IntegerField()),
                ('solved', models.IntegerField()),
                ('rating_change', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
