# Generated by Django 2.2.3 on 2019-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190803_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcescontest',
            name='contest_id',
            field=models.IntegerField(default=0),
        ),
    ]
